# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [1]:
import numpy as np
import sys

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [2]:
python_list = [0] * 1000
sys.getsizeof(python_list)

8056

In [3]:
numpy_array = np.array(python_list, dtype=np.int8)
sys.getsizeof(numpy_array)

1112

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [4]:
small_float_array = np.arange(11, dtype=np.float16)
small_float_array[[0, 2, -1]]

array([ 0.,  2., 10.], dtype=float16)

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [5]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
subsequence_sum = array[[0, 1, 4, -1]].sum()
subsequence_sum

np.float64(27.0)

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [6]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [15]:
mean_columns = np.mean(A, axis=0)
mean_columns

array([2. , 8.4])

### Task 5.2 Get the standard deviation by `y` axis

In [16]:
std_dev_rows = np.std(A, axis=1)
std_dev_rows

array([2.5, 3. , 4. , 3.5, 3. ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [17]:
sum_by_rows = np.sum(A, axis=1)
sum_by_rows

array([ 7, 10, 14, 13,  8])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [10]:
sub_matrix1 = A[:2]
sub_matrix1

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [11]:
sub_matrix2 = A[[0, 2, -1]]
sub_matrix2

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [12]:
# Python code
%time python_list = [i for i in range(1000000)]

CPU times: total: 46.9 ms
Wall time: 93.7 ms


In [13]:
%time np.array(python_list, np.int32)

CPU times: total: 62.5 ms
Wall time: 70 ms


array([     0,      1,      2, ..., 999997, 999998, 999999], dtype=int32)

### Task 6.2

In [14]:
# Python code
def multiply_elements_of_list(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]


%timeit result = multiply_elements_of_list(vector1, vector2)
result

525 ns ± 57.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


NameError: name 'result' is not defined

In [ ]:
vector3 = np.array([1, 2, 3], dtype=np.int8)
vector4 = np.array([4, 5, 6], dtype=np.int8)

%timeit result = np.dot(vector3, vector4)
result

### Task 6.3

In [ ]:
# Python code
def elementwise_multiply(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]


%timeit result = unknown_signature(matrix1, matrix2)

In [ ]:
matrix3 = np.array([[1, 2], [3, 4]])
matrix4 = np.array([[5, 6], [7, 8]])

%timeit result = np.multiply(matrix3, matrix4)
result

### Task 6.4

In [ ]:
# Python code
def calculate_average(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]
%timeit result = calculate_average(lst)
result

In [ ]:
lst_np = np.array([1, 2, 3, 4, 5], np.int8)
%timeit result = np.mean(lst_np)
result

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [ ]:
# Python code
def apply_mask_and_replace(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
%timeit apply_mask_and_replace(lst, mask, new_value)
lst

In [ ]:
lst_num = np.array([1, 2, 3, 4, 5], dtype=np.int8)
mask = np.array([True, False, True, False, True], dtype=bool)
new_value = 0

lst[mask] = new_value

%timeit lst[mask] = new_value
lst

### Task 7.2

In [ ]:
# Python code
def bitwise_operations(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
%timeit bitwise_operations(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or =  bitwise_operations(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

In [ ]:
def bitwise_operations_numpy(lst1, lst2):
    bitwise_complement = np.bitwise_not(lst1)
    bitwise_and = np.bitwise_and(lst1, lst2)
    bitwise_or = np.bitwise_or(lst1, lst2)
    return bitwise_complement, bitwise_and, bitwise_or


list1 = np.array([5, 2, 7, 4, 9], dtype=np.int8)
list2 = np.array([3, 6, 1, 8, 10], dtype=np.int8)

%timeit bitwise_operations_numpy(list1, list2)

result_bitwise_complement, result_bitwise_and, result_bitwise_or = bitwise_operations_numpy(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

### Task 7.3 Optional

In [ ]:
# Python code
def modified_even_numbers(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]

%timeit modified_even_numbers(my_list)
modified_even_numbers(my_list)

In [ ]:
def modified_even_numbers_numpy(lst):
    lst = np.array(lst, dtype=np.int8)
    mask = (lst % 2 == 0) & ((lst % 3 == 0) | (lst > 10))
    modified_nums = (lst[mask] ^ 7) + 2
    return modified_nums.tolist()

%timeit modified_even_numbers_numpy(my_list)
modified_even_numbers_numpy(my_list)